tasks:
  - name: Install npm dependencies
    init: npm install
    command: echo 'All npm dependencies installation completed.'

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
