name: "json2markdown"
description: "json to markdown link"
branding:
  icon: "code"
  color: "blue"
inputs:
  columns:
    description: "how many columns"
    required: false
    default: "2"
  json-file-path:
    description: "json file to load"
    required: true
    default: "Data.json"
  github-token:
    description: "github token"
    required: true
  html-cell:
    description: "html for the table cell"
    required: true
  object-field-names:
    description: "array of object field names from your json objects"
    required: true
  file-to-use:
    description: "file to push the changes to"
    required: false
    default: "README.md"
runs:
  using: "node12"
  main: "dist/index.js"
